import streamlit as st

st.session_state["last_page_visited"] = "home/explainer.py"

#Messaging
st.title("What is this?")

st.write(
    """
    ***This*** is a custom webapp built on **Python**, **Streamlit**, and **OpenAI**.
    
    Soon, you'll meet **Agora**, an AI assistant specialized in legal research.

    In **Open Chat**, Agora refuses to write complete drafts or state opinions.
    Instead, Agora answers legal questions factually, sifts through files, and leads the user in the 
    right direction.

    For additional control, **Guided Chat** manages what can be inputted. Prompts
    are generated by another assistant, Queequeg (***Q***ueeque***g*** : ***Q***uery ***g***enerator).
    Queequeg works behind the scenes, reading the inputted files and the conversation with Agora, to suggest prompts.

    For navigation, use the buttons to follow the demonstration flow I've set, 
    or navigate freely using the side menu, accessible by the arrow on the top left.

    Next, you'll choose some preferences, and go on a tour of the platform. 
    """
)


st.divider()


#Nav
foot_lt, foot_rt = st.columns(2)
with foot_lt:
    if st.button("<- Welcome", use_container_width=True):
        st.switch_page("home/welcome.py")

with foot_rt:
    if st.button("Preferences ->", use_container_width=True, type="primary"):
        st.switch_page("tools/preferences.py")

