openai_key = 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

anthropic_key = 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